### ISSUE TITLE
Failed to compile on latest nightly

### ISSUE THREAD

**Issue by IndianBoy42** [Kampfkarren/full-moon#192]
```
error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:1976 ~ full_moon[5c09]::ast::parsers::{impl#225}::parse::{closure#0}), const_param_did: None }) (end of phase Optimization) at bb63[0]:
use of local _155, which has no storage here
    --> /home/amedhi/.cargo/registry/src/github.com-1ecc6299db9ec823/full_moon-0.13.1/src/ast/parsers.rs:1858:4
     |
1858 |               }
     |               ^
...
1865 | / make_op_parser!(BinOp, ParseBinOp,
1866 | |     {
1867 | |         And,
1868 | |         Caret,
...    |
1882 | |     }
1883 | | );
     | |__- in this macro invocation
     |
     = note: delayed at compiler/rustc_mir/src/transform/validate.rs:121:36
     = note: this error: internal compiler error originates in the macro `make_op_parser` (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:1990 ~ full_moon[5c09]::ast::parsers::{impl#230}::parse::{closure#0}), const_param_did: None }) (end of phase Optimization) at bb15[0]:
use of local _35, which has no storage here
    --> /home/amedhi/.cargo/registry/src/github.com-1ecc6299db9ec823/full_moon-0.13.1/src/ast/parsers.rs:1858:4
     |
1858 |               }
     |               ^
...
1885 | / make_op_parser!(UnOp, ParseUnOp,
1886 | |     {
1887 | |         Minus,
1888 | |         Not,
1889 | |         Hash,
1890 | |     }
1891 | | );
     | |__- in this macro invocation
     |
     = note: delayed at compiler/rustc_mir/src/transform/validate.rs:121:36
     = note: this error: internal compiler error originates in the macro `make_op_parser` (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1166:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (29ef6cf16 2021-08-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z share-generics=y -C opt-level=3 -C panic=abort -C linker-plugin-lto -C link-arg=-fuse-ld=lld -C target-cpu=native --crate-type rlib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `full_moon`
warning: build failed, waiting for other jobs to finish...
error: failed to compile `stylua v0.10.1`, intermediate artifacts can be found at `/tmp/cargo-install6JadEz
```
The rustc version is:
```
note: rustc 1.56.0-nightly (29ef6cf16 2021-08-31) running on x86_64-unknown-linux-gnu
```

Probably a compiler bug should be submitted but they generally want a minimum reproducible example which I am not familiar enough with the codebase

**Comment by Kampfkarren** [comment]
This is weird, I'm gonna subscribe to the issue you filed for Rust to see if there's anything we can (or should, if it's a Rust bug) do about this.

**Comment by Kampfkarren** [comment]
Looks like the regression was fixed, according to my notifications anyway.
